[tool.poetry]
name = "ureport"
version = "1.2.51"
description = "U-Report dashboard built on data collected by RapidPro"
authors = ["Nyaruka Ltd <code@nyaruka.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.7"
smartmin = "^4.2.2"
rapidpro-dash = "^1.10.3"
colorama = "^0.4.3"
celery = "^5.1"
django-compressor = "^4.0"
django-debug-toolbar = "3.2.4"
django-digest = "^1.13"
django-rosetta = "^0.8.1"
django-storages = "^1.6.6"
django-rest-swagger = "^2.2.0"
djangorestframework = "3.11.2"
dj-database-url = "^0.5.0"
boto3 = "^1.7.67"
Pillow = "^9.4.0"
gunicorn = "^20.1.0"
pisa = "^3.0.33"
sentry-sdk = "^0.19.5"
django-redis = "^5.2.0"
psycopg2-binary = "^2.9.5"
xlutils = "^2.0.0"
mock = "^2.0.0"
django-hamlpy = "^1.4.4"
pycountry = "^18.5.26"
django-countries = "^7.2.1"
GitPython = "^2.1.11"
regex = "^2020.9.27"
rapidpro-python = "^2.9.0"
feedparser = "^6.0.2"
Markdown = "^2.6.11"
iso8601 = "^0.1.12"
sorl-thumbnail = "^12.9.0"
stop_words = "^2018.7.23"


[tool.poetry.dev-dependencies]
black = "^22.3"
isort = "^5.9.3"
flake8 = "^3.7.9"
codecov = "^2.1.11"

[tool.black]
line-length = 119

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
